# Generated by Django 2.2.10 on 2020-08-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, default='0000000000', null=True, verbose_name='Téléphone'),
        ),
    ]
