# Generated by Django 2.2.10 on 2020-04-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200402_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(default='test', max_length=256, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(default='test', max_length=256, verbose_name='Nom de famille'),
            preserve_default=False,
        ),
    ]
