# Generated by Django 2.2.10 on 2020-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200426_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='default company', max_length=256, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=12, verbose_name='Téléphone'),
        ),
    ]
