# Generated by Django 2.2.10 on 2020-07-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200622_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_password',
            field=models.BooleanField(default=False),
        ),
    ]
