# Generated by Django 2.2.10 on 2020-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_title', models.CharField(max_length=200, verbose_name="titre page d'accueil")),
                ('homepage_first_img', models.ImageField(default='/default.jpg', upload_to='static')),
                ('homepage_title_description', models.CharField(max_length=200, verbose_name="titre page d'accueil")),
                ('homepage_content_description', models.CharField(max_length=200, verbose_name="titre page d'accueil")),
                ('homepage_content_img', models.ImageField(default='/default.jpg', upload_to='static')),
            ],
            options={
                'verbose_name': 'Contenu du site',
                'verbose_name_plural': 'Contenus du site',
            },
        ),
    ]
