# Generated by Django 2.2.10 on 2020-07-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_title', models.CharField(default='default', max_length=200, verbose_name="Titre page d'accueil")),
                ('homepage_first_img', models.ImageField(default='/default.jpg', upload_to='static')),
                ('homepage_title_description', models.CharField(default='default', max_length=200, verbose_name="Titre bloc page d'accueil")),
                ('homepage_content_description', models.TextField(default='default', verbose_name="Contenu bloc page d'accueil")),
                ('homepage_content_img', models.ImageField(default='/default.jpg', upload_to='static')),
                ('concept_firstblock_title', models.CharField(default='default', max_length=200, verbose_name='Titre premier bloc')),
                ('concept_firstblock_content', models.TextField(default='default', verbose_name='Titre du second bloc')),
                ('concept_firstblock_background', models.ImageField(default='/default.jpg', upload_to='static')),
                ('concept_firstblock_img', models.ImageField(default='/default.jpg', upload_to='static')),
                ('concept_secondblock_title', models.CharField(default='default', max_length=200, verbose_name='Titre du second bloc')),
                ('concept_secondblock_content', models.TextField(default='default', verbose_name='Contenu du second bloc')),
                ('concept_thirdblock_title', models.CharField(default='default', max_length=200, verbose_name='Titre du troisième bloc')),
                ('concept_thirdblock_firstservice', models.CharField(default='default', max_length=200, verbose_name='Contenu premier service')),
                ('concept_thirdblock_secondservice', models.CharField(default='default', max_length=200, verbose_name='Contenu second service')),
                ('concept_thirdblock_thirdservice', models.CharField(default='default', max_length=200, verbose_name='Contenu troisième service')),
            ],
            options={
                'verbose_name': 'Contenu du site',
                'verbose_name_plural': 'Contenus du site',
            },
        ),
    ]
