# Generated by Django 2.2.10 on 2020-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='concept_firstblock_background',
            field=models.ImageField(default='/default.jpg', upload_to='static'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_firstblock_content',
            field=models.TextField(default='default', verbose_name='Titre du second bloc'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_firstblock_img',
            field=models.ImageField(default='/default.jpg', upload_to='static'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_firstblock_title',
            field=models.CharField(default='default', max_length=200, verbose_name='Titre premier bloc'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_secondblock_content',
            field=models.TextField(default='default', verbose_name='Contenu du second bloc'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_secondblock_title',
            field=models.CharField(default='default', max_length=200, verbose_name='Titre du second bloc'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_thirdblock_firstservice',
            field=models.CharField(default='default', max_length=200, verbose_name='Contenu premier service'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_thirdblock_secondservice',
            field=models.CharField(default='default', max_length=200, verbose_name='Contenu second service'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_thirdblock_thirdservice',
            field=models.CharField(default='default', max_length=200, verbose_name='Contenu troisième service'),
        ),
        migrations.AddField(
            model_name='content',
            name='concept_thirdblock_title',
            field=models.CharField(default='default', max_length=200, verbose_name='Titre du troisième bloc'),
        ),
        migrations.AlterField(
            model_name='content',
            name='homepage_content_description',
            field=models.TextField(default='default', verbose_name="Contenu bloc page d'accueil"),
        ),
        migrations.AlterField(
            model_name='content',
            name='homepage_title',
            field=models.CharField(default='default', max_length=200, verbose_name="Titre page d'accueil"),
        ),
        migrations.AlterField(
            model_name='content',
            name='homepage_title_description',
            field=models.CharField(default='default', max_length=200, verbose_name="Titre bloc page d'accueil"),
        ),
    ]
