# Generated by Django 2.2.10 on 2020-02-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('height', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Hauteur (cm)')),
                ('width', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Largeur (cm)')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist', verbose_name='Artiste')),
            ],
            options={
                'verbose_name': 'Oeuvre',
                'verbose_name_plural': 'Oeuvres',
            },
        ),
    ]
