# Generated by Django 2.2.10 on 2020-04-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='photo',
            field=models.ImageField(default='/default.jpg', upload_to='artworks'),
        ),
    ]
