# Generated by Django 2.2.10 on 2020-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Prix (€)'),
        ),
    ]
