# Generated by Django 2.2.10 on 2020-06-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20200622_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Style de l'oeuvre",
                'verbose_name_plural': 'Style des oeuvres',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='style',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork_Style', verbose_name='Style'),
        ),
    ]
