# Generated by Django 2.2.10 on 2020-06-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20200622_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Catégorie de l'oeuvre",
                'verbose_name_plural': 'Catégories des oeuvres',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artworks.Artwork_Category', verbose_name='Catégorie'),
        ),
    ]
