# Generated by Django 2.2.10 on 2020-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_auto_20200818_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='introduction',
            field=models.CharField(default='default', max_length=200, verbose_name="Introduction de l'oeuvre"),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='spotlight',
            field=models.BooleanField(default=False, verbose_name='Mettre en avant'),
        ),
    ]
