# Generated by Django 2.2.10 on 2020-08-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_auto_20200819_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.Artwork_Category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='storage_place',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.Artwork_Storage_Place', verbose_name='Lieu de stockage'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.Artwork_Style', verbose_name='Style'),
        ),
    ]
