# Generated by Django 2.2.10 on 2020-06-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_auto_20200623_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='state',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Non loué'), (2, 'Loué')], default=1, null=True),
        ),
    ]
