# Generated by Django 2.2.10 on 2020-07-07 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0009_artwork_spotlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='timer',
            field=models.DateField(default=datetime.datetime(2020, 7, 7, 14, 10, 20, 898633, tzinfo=utc), verbose_name='Timer'),
        ),
    ]
