# Generated by Django 2.2.10 on 2020-07-07 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0010_artwork_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 14, 27, 51, 225346, tzinfo=utc), verbose_name='Timer'),
        ),
    ]
