# Generated by Django 2.2.10 on 2020-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_auto_20200707_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='timer',
            field=models.DateTimeField(verbose_name='Timer'),
        ),
    ]
