# Generated by Django 2.2.10 on 2020-07-07 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_auto_20200707_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='timer',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 14, 31, 9, 257379, tzinfo=utc), verbose_name='Timer'),
        ),
    ]
