# Generated by Django 2.2.10 on 2020-07-07 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_auto_20200707_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='timer',
            field=models.DateField(default=datetime.datetime(2020, 7, 7, 15, 6, 49, 120884, tzinfo=utc), verbose_name='Timer'),
        ),
    ]
