# Generated by Django 2.2.10 on 2020-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0014_auto_20200707_1706'),
        ('artworks', '0010_auto_20200707_1355'),
    ]

    operations = [
    ]
