# Generated by Django 2.2.10 on 2020-07-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0015_merge_20200708_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='timer',
            field=models.DateField(blank=True, null=True, verbose_name='Timer'),
        ),
    ]
