# Generated by Django 2.2.10 on 2020-07-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_order_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
