# Generated by Django 2.2.10 on 2020-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Durée en mois')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Taux')),
            ],
            options={
                'verbose_name': 'Taux',
                'verbose_name_plural': 'Taux',
            },
        ),
    ]
