# Generated by Django 2.2.10 on 2020-06-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='duration',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Durée en mois'),
        ),
    ]
