# Generated by Django 2.2.10 on 2020-07-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=200, verbose_name='Nom de famille')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom d'artiste")),
                ('spotlight', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artiste',
                'verbose_name_plural': 'Artistes',
            },
        ),
    ]
