# Generated by Django 2.2.10 on 2020-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotlight',
            field=models.BooleanField(default=False, verbose_name='Mise en avant'),
        ),
    ]
