# Generated by Django 2.2.10 on 2020-08-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_description',
            field=models.CharField(default='default', max_length=200, verbose_name="Description de l'artiste"),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_universe',
            field=models.CharField(default='default', max_length=200, verbose_name="Description de l'artiste"),
        ),
    ]
