# Generated by Django 2.2.10 on 2020-08-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20200817_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_universe',
            field=models.CharField(default='default', max_length=200, verbose_name='Description de son univers'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotlight',
            field=models.BooleanField(default=False, verbose_name='Mettre en avant'),
        ),
    ]
