# Generated by Django 2.2.10 on 2020-07-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderartworkrate',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
