# Generated by Django 2.2.10 on 2020-07-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200701_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'En attente'), (2, 'Confirmée')], default=1),
        ),
    ]
