# Generated by Django 2.2.10 on 2020-07-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_artworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artworks',
        ),
    ]
