# Generated by Django 2.2.10 on 2020-07-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200701_1659'),
        ('orders', '0004_order_state'),
    ]

    operations = [
    ]
