# Generated by Django 2.2.10 on 2020-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
        ('rates', '0001_initial'),
        ('orders', '0005_remove_order_artworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='artworks',
            field=models.ManyToManyField(related_name='order_artwork', through='orders.OrderArtworkRate', to='artworks.Artwork'),
        ),
        migrations.AddField(
            model_name='order',
            name='rates',
            field=models.ManyToManyField(related_name='order_artwork', through='orders.OrderArtworkRate', to='rates.Rate'),
        ),
    ]
