# Generated by Django 2.2.10 on 2020-07-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20200701_2300'),
        ('orders', '0005_merge_20200701_2055'),
    ]

    operations = [
    ]
