# Generated by Django 2.2.10 on 2020-07-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200708_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artworks',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rates',
        ),
    ]
