# Generated by Django 2.2.10 on 2020-07-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200707_0833'),
        ('orders', '0006_auto_20200707_0943'),
    ]

    operations = [
    ]
