# Generated by Django 2.2.10 on 2020-07-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_auto_20200707_1355'),
        ('orders', '0009_auto_20200707_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_rate', to='rates.Rate'),
        ),
    ]
